services:
  luigid:
    build:
      args:
      - SSH_PRIVATE_KEY
      context: .
      dockerfile: Dockerfile
    command: luigid
    image: luigiui:1.0
    ports:
    - 8082:8082
  pipeline:
    build:
      context: .
    command: bash -c "LUIGI_CONFIG_PATH=luigi.cfg python -m luigi --module main GenerateExceptionReports
      --workers=10 --scheduler-host luigid"
    depends_on:
    - luigid
    image: luigiui:1.0
    volumes:
    - ./app:/home/pipeline
    - ./project.yaml:/home/pipeline/project.yaml
    - /Users/stephen/Yellow Canary/Yellow Canary - Documents/Clients/Projects/HSF/Sunflower/01_Data:/home/pipeline/sharedata/
version: '3'
