project: allium
version: 1.0
sharepoint: /Clients/Projects/HSF/Sunflower/01_Data
users: /Users/stephen/Yellow Canary/Yellow Canary - Documents

docker:
  container:
    services:
      luigid:
        build:
          context: .
          dockerfile: Dockerfile
        command: luigid 
        image: luigiui:1.0
        ports:
        - 8082:8082
        
      pipeline:
          image: luigiui:1.0
          depends_on:
            - luigid
          volumes:
            - ./app:/home/pipeline
            - ./project.yaml:/home/pipeline/project.yaml
        
          build:
            context: .
          command: bash -c "LUIGI_CONFIG_PATH=luigi.cfg python -m luigi --module main GenerateExceptionReports --workers=10 --scheduler-host luigid"
    version: '3'
  image:
    - FROM python:3.9.7-slim
    - ENV PYTHONPATH=/home/pipeline:$PYTHONPATH
    - RUN mkdir -p /home/pipeline
    - COPY ./app /home/pipeline/
    - RUN pip install -r /home/pipeline/requirements.txt
    - WORKDIR /home/pipeline

raw:
  payslips: {include: ["payslip","cohort 1"], exclude: ["sample","sunflower"], broken: []}
  timesheets: {include: ["to","cohort 1"], exclude: ["sample","sunflower","locations","payslips"], broken: []}
  master: {include: ["payslip","cohort 1"], exclude: ["sample","sunflower"], broken: []}

staging:
  payslips: [
             {staging: 'EmployeeCode',         raw: 'ID Number',                  type: 'object',         tests: [],                      plugin: {}}
            ,{staging: 'PayslipCode',          raw: 'create_PayslipCode',         type: 'object',         tests: [],                      plugin: {name: 'PayslipCode', ref: [], switch: True}}
            ,{staging: 'PaysliplineCode',      raw: 'create_PaysliplineCode',     type: 'object',         tests: [],                      plugin: {name: 'PaysliplineCode', ref: ['EmployeeCode', 'PeriodEndDate'], switch: True}}
            ,{staging: 'PeriodStartDate',      raw: 'create_PeriodStartDate',     type: 'datetime64[ns]', tests: ['date'],                plugin: {name: 'PeriodStartDate', ref: ['PayFrequency', 'PeriodEndDate'], switch: True}}
            ,{staging: 'PeriodEndDate',        raw: 'Period Ending Date',         type: 'datetime64[ns]', tests: ['date'],                plugin: {}}
            ,{staging: 'PayFrequency',         raw: 'Pay Frequency',              type: 'object',         tests: [],                      plugin: {}}
            ,{staging: 'Paycode',              raw: 'Hours or A/D Code Desc',     type: 'object',         tests: ['inscope'],             plugin: {}}
            ,{staging: 'Hours',                raw: 'Number of Units',            type: 'float64',        tests: ['numeric'],             plugin: {}}
            ,{staging: 'Amount',               raw: 'Value',                      type: 'float64',        tests: ['numeric'],             plugin: {}}
            ,{staging: 'EmployeeType',         raw: 'Employment Type Code Desc',  type: 'object',         tests: ['inscope'],             plugin: {}}
            ,{staging: 'EmployeeClassication', raw: 'Job Title Code Description', type: 'object',         tests: ['inscope'],             plugin: {}}
            ,{staging: 'DateOfBirth',          raw: 'Date of Birth',              type: 'datetime64[ns]', tests: ['date'],                plugin: {}}
            ,{staging: 'BaseHours',            raw: 'Base Hours',                 type: 'float64',        tests: ['numeric','positive'],  plugin: {}}
            ,{staging: 'Site',                 raw: 'Account Code Description',   type: 'object',         tests: [],                      plugin: {}}
            ,{staging: 'Source',               raw: 'source',                     type: 'object',         tests: [],                      plugin: {}}
            ]

  timesheets: [
             {staging: 'EmployeeCode',         raw: 'Export Code',                type: 'object',         tests: [],                      plugin: {}}
            ,{staging: 'Award',                raw: 'create_award',               type: 'object',         tests: ['inscope'],             plugin: {name: 'Award', ref: [], switch: True}}
            ,{staging: 'Date',                 raw: 'Date',                       type: 'datetime64[ns]', tests: ['date'],                plugin: {}}
            ,{staging: 'ClockedIn',            raw: 'Pay Start',                  type: 'datetime64[ns]', tests: ['date'],                plugin: {}}
            ,{staging: 'ClockedOut',           raw: 'Pay End',                    type: 'datetime64[ns]', tests: ['date'],                plugin: {}}
            ,{staging: 'RosteredIn',           raw: 'Sched Start',                type: 'datetime64[ns]', tests: ['date'],                plugin: {}}
            ,{staging: 'RosteredOut',          raw: 'Sched End',                  type: 'datetime64[ns]', tests: ['date'],                plugin: {}}
            ,{staging: 'Break',                raw: 'Break',                      type: 'object',         tests: [],                      plugin: {}}
            ,{staging: 'Region',               raw: 'Site',                       type: 'object',         tests: [],                      plugin: {}}
            ,{staging: 'ShiftRole',            raw: 'Role',                       type: 'object',         tests: ['inscope'],             plugin: {}}
            ,{staging: 'ShiftClassification',  raw: 'Employee Type',              type: 'object',         tests: ['inscope'],             plugin: {}}
            ,{staging: 'Source',               raw: 'source',                     type: 'object',         tests: [],                      plugin: {}}
            ]

sentinel:
  configuration: {ClientId: "sunflower"}
                
  EmployeeBaseFile: 
    {
    data: ['EmployeeCode', 'StartDate','EndDate','DateOfBirth', 'Source''string'],
    type: ['object','iso', 'iso', 'iso', 'object']
    }

  EmployeeClassifications: 
    {
    data: ['EmployeeCode', 'StartDate', 'EndDate', 'Classification'],
    type: ['object','iso', 'iso', 'object']
    }

  EmployeeEmploymentTypes:
    {
      data: ['EmployeeCode', 'StartDate', 'EndDate', 'EmploymentType'], # Employment type: Casual,FullTime,PartTime
      type: ['object','iso', 'iso', 'object']
    }

  Leave: #supports additional columns
    {
      data: ['EmployeeCode', 'Start', 'End', 'PayCode', 'Source'],  #paycode: PaidLeave, AnnualLeave
      type: ['object','iso', 'iso', 'object', object']
    }
                                        
  Payslips: #supports additional columns
    {
      data: ['EmployeeCode','PayslipCode','PayslipLineCode', 'PeriodStart','PeriodEnd', #paycode: Basepay / After6am / Holiday / OT250 etc
             'PayCode','Description', 'Hours', 'Amount','Classification', 'Source'], 
      type: ['object','object','object','iso', 'iso', 
             'object','object','float', float','object','object'],
      Classification: ['Ordinary','Overtime','Penalty','CasualLoading','Leave','Allowance']
    }
                                      
  Timesheets:  #supports additional columns
    {
      data: ['EmployeeCode','Award','ClockedIn', 'ClockedOut','RosteredIn', #paycode: Basepay / After6am / Holiday / OT250 etc
             'RosteredOut','UnpaidBreaks', 'Region', 'Source'], 
      type: ['object','object','iso','iso', 'iso', 
             'iso','object','object','object'],
      Region: ['National','Qld','Nsw','Act','Vic','Tas','Nt','Sa','Wa','Brisbane']
    }